### ISSUE TITLE
Please don't use/advertise .dev top level domain for private use

### ISSUE THREAD

**Issue by okket** [luisfarzati/localdots#1]
The TLD .dev is an official TLD, please don't use for local/LAN only usage.

**Comment by okket** [comment]
Sorry, I was confused, I think I get now what your tool does.

**Comment by lufzle** [comment]
Hi @okket , this is actually a good point. You know, there was a section around this topic that didn't end up in the README because I decided to discard it (not really relevant, I thought).

The fact that you mention this means maybe it wasn't a bad idea at all. So I added it: https://github.com/luisfarzati/localdots#about-domains

IMHO while I can see your point, I haven't seen any problems using a non-special TLD as long as it's scoped to your local machine (and not implying LAN here) and of course you don't use any common domain that may affect your reach to services (Google, Apple, AWS, cdns...).

Thanks for bringing this up!
